diff --git a/config/MSRGCN/h36m/demo.yaml b/config/MSRGCN/h36m/demo.yaml
index 30f1d82..bbf15e6 100644
--- a/config/MSRGCN/h36m/demo.yaml
+++ b/config/MSRGCN/h36m/demo.yaml
@@ -12,7 +12,7 @@ feeder: feeder.MSRGCN.datas.h36m.H36MMotionDataset
 path_to_data: /share/zhangjinrong//human_motion_prediction/data/h3.6m/dataset
 train_manner: "all" # ["walking", "eating", "smoking", "discussion", "directions","greeting", "phoning", "posing", "purchases", "sitting", "sittingdown", "takingphoto", "waiting", "walkingdog", "walkingtogether"]
 test_manner: "all" # ["walking", "eating", "smoking", "discussion", "directions","greeting", "phoning", "posing", "purchases", "sitting", "sittingdown", "takingphoto", "waiting", "walkingdog", "walkingtogether"]
-subs: [[1, 6, 7, 8, 9], [5], [11]] # 对应data_path下的数据文件夹[[1, 6, 7, 8, 9], [5], [11]]
+subs: [[1], [5], [11]] # 对应data_path下的数据文件夹[[1, 6, 7, 8, 9], [5], [11]]
 train_split: 0 # 对应subs中的选项
 teat_split: 1
 validation_split: 2
diff --git a/main.py b/main.py
index a4c00b8..7df2b5a 100644
--- a/main.py
+++ b/main.py
@@ -5,6 +5,7 @@ import pprint
 import argparse
 import pandas as pd
 import wandb
+import datetime
 
 from runner import Runner
 
@@ -60,9 +61,38 @@ elif args.exp_name == "cmu":
 
 if args.is_load:
     runner.restore(args.modle_path)
+    file = open(args.modle_path+"run_id.txt", 'r')
+    run_id = file.readlines()
+    run = wandb.init(project=args.wandb_project, id=run_id, resume='must')
 
 if args.is_train:
+    # wandb设置
+    nowtime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
+    wandb.init(project=args.wandb_project, config=vars(args), name=nowtime, save_code=True)
+    run_id = wandb.run.id
+    with open(args.work_dir+"run_id.txt", 'w') as f:
+        f.write(run_id)
+    
+    # wandb版本管理
+    # wandb保存配置文件
+    arti_config = wandb.Artifact("config", type='yaml')
+    arti_config.add_file(args.work_dir + "/config.yaml")
+    wandb.log_artifact(arti_config)
+    # wandb保存模型文件
+    arti_modle = wandb.Artifact("modle", type='code')
+    x = args.model.split('.')
+    arti_modle.add_file(x[0] + '/' + x[1] + '/' + x[2] + '.py')
+    wandb.log_artifact(arti_modle)
+    # wandb保存运行文件
+    arti_runner = wandb.Artifact("runner", type='code')
+    arti_config.add_file("/runner/runner.py")
+    wandb.log_artifact(arti_runner)
+    
+    # 开始训练
     runner.run()
+    
+    # wandb结束
+    wandb.finish()
 else:
     errs = runner.test()
 
diff --git a/runner/__pycache__/runner.cpython-310.pyc b/runner/__pycache__/runner.cpython-310.pyc
index 79b97ea..8ed0c81 100644
Binary files a/runner/__pycache__/runner.cpython-310.pyc and b/runner/__pycache__/runner.cpython-310.pyc differ
diff --git a/runner/runner.py b/runner/runner.py
index 3df34be..5f4cb53 100644
--- a/runner/runner.py
+++ b/runner/runner.py
@@ -192,8 +192,7 @@ class Runner():
         return total_loss
     
     def run(self):
-        nowtime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
-        wandb.init(project=self.args.wandb_project, config=vars(self.args), name=nowtime, save_code=True)
+        
         for epoch in range(self.start_epoch, self.args.n_epoch + 1):
 
             if epoch % 2 == 0:
@@ -223,4 +222,4 @@ class Runner():
                 loss_l2_test = self.test(epoch)
 
                 print('Epoch: {},  LR: {}, Current err test avg: {}'.format(epoch, self.lr, np.mean(loss_l2_test)))
-        wandb.finish()
\ No newline at end of file
+        
\ No newline at end of file
diff --git a/wandb/debug-internal.log b/wandb/debug-internal.log
index 6cf6ca9..77efefd 120000
--- a/wandb/debug-internal.log
+++ b/wandb/debug-internal.log
@@ -1 +1 @@
-run-20230214_171449-zypo66js/logs/debug-internal.log
\ No newline at end of file
+run-20230214_182138-r2ltuaiq/logs/debug-internal.log
\ No newline at end of file
diff --git a/wandb/debug.log b/wandb/debug.log
index aec43ab..1550e19 120000
--- a/wandb/debug.log
+++ b/wandb/debug.log
@@ -1 +1 @@
-run-20230214_171449-zypo66js/logs/debug.log
\ No newline at end of file
+run-20230214_182138-r2ltuaiq/logs/debug.log
\ No newline at end of file
diff --git a/wandb/latest-run b/wandb/latest-run
index d6df2ed..8ade958 120000
--- a/wandb/latest-run
+++ b/wandb/latest-run
@@ -1 +1 @@
-run-20230214_171449-zypo66js
\ No newline at end of file
+run-20230214_182138-r2ltuaiq
\ No newline at end of file
diff --git a/wandb/run-20230214_170826-5jufynrf/logs/debug-internal.log b/wandb/run-20230214_170826-5jufynrf/logs/debug-internal.log
index 8fa2b52..63261b6 100644
--- a/wandb/run-20230214_170826-5jufynrf/logs/debug-internal.log
+++ b/wandb/run-20230214_170826-5jufynrf/logs/debug-internal.log
@@ -116057,3 +116057,152 @@
 2023-02-14 17:27:48,259 ERROR   StreamThr :57839 [internal.py:wandb_internal():153] Internal process shutdown.
 2023-02-14 17:27:48,790 INFO    HandlerThread:57839 [handler.py:finish():841] shutting down handler
 2023-02-14 17:27:49,153 INFO    WriterThread:57839 [datastore.py:close():299] close: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/run-5jufynrf.wandb
+2023-02-14 17:36:30,821 ERROR   Thread-12 (_thread_body):57839 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/zhangjinrong/MSRGCN/5jufynrf/artifact/366178353/wandb_manifest.json?Expires=1676452804&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=NxciPN7d%2BIaX9afUHomXg3zPwQpdtkBwhXi3S9XmbxNsz35N%2BWIT6xoZJ%2BEu7OAK7lFEjOOlQ64%2FvZlzdGVSTZuPw4ZHaVjkH7SCHd4EY%2FDNy54x0ukm060ExzTcIGc0sGCF4%2BXJ%2B4HO4hqVehwR8PDzE1prxJmUcDpMpnpn6MYIlew5n6SBfzj8UfviyUaHpT56EpHp3HevfiJH4TTBYX1J4HYX0zJ1qVeJVmnb2OuinSMokNrdSCrlOlzUIu4LMnfNDM9CgAeqOTn3HC9NFgc35NupKz7o7AMqOndyXRIObYzrbD0sxylUtEo6mxA1ApC4j6JQA8U%2BZ3mzVgm%2BBw%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
+2023-02-14 17:36:30,821 ERROR   Thread-12 (_thread_body):57839 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'R6rBL2fG5uEXR5ef0rZHzA==', 'Content-Length': '683'}
+2023-02-14 17:36:30,821 ERROR   Thread-12 (_thread_body):57839 [internal_api.py:upload_file():2008] upload_file response body: 
+2023-02-14 17:36:33,081 ERROR   Thread-12 (_thread_body):57839 [internal_api.py:execute():245] 404 response executing GraphQL.
+2023-02-14 17:36:33,082 ERROR   Thread-12 (_thread_body):57839 [internal_api.py:execute():246] {"errors":[{"message":"failed to find project 37327736","path":["commitArtifact"]}],"data":{"commitArtifact":null}}
+2023-02-14 17:36:33,083 ERROR   SenderThread:57839 [sender.py:send_artifact():1419] send_artifact: failed for artifact "job/job-https___github.com_wuyefa_Torch_Template.git_main.py": Permission denied, ask the project owner to grant you access
+2023-02-14 17:36:33,083 INFO    SenderThread:57839 [sender.py:finish():1493] shutting down sender
+2023-02-14 17:36:33,083 INFO    SenderThread:57839 [dir_watcher.py:finish():362] shutting down directory watcher
+2023-02-14 17:36:33,338 INFO    SenderThread:57839 [dir_watcher.py:finish():392] scan: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files
+2023-02-14 17:36:33,338 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/wandb-metadata.json wandb-metadata.json
+2023-02-14 17:36:33,338 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/wandb-summary.json wandb-summary.json
+2023-02-14 17:36:33,339 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/diff.patch diff.patch
+2023-02-14 17:36:33,339 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/requirements.txt requirements.txt
+2023-02-14 17:36:33,339 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/conda-environment.yaml conda-environment.yaml
+2023-02-14 17:36:33,339 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/config.yaml config.yaml
+2023-02-14 17:36:33,339 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/output.log output.log
+2023-02-14 17:36:33,345 INFO    SenderThread:57839 [dir_watcher.py:finish():406] scan save: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/code/main.py code/main.py
+2023-02-14 17:36:33,345 INFO    SenderThread:57839 [file_pusher.py:finish():162] shutting down file pusher
+2023-02-14 17:36:33,346 INFO    SenderThread:57839 [file_pusher.py:join():167] waiting for file pusher
+2023-02-14 17:36:33,712 ERROR   Thread-12 (_thread_body):57839 [step_upload.py:_handle_event():141] Failed to upload file: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/wandb-summary.json
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+TypeError: 'NoneType' object is not subscriptable
+
+During handling of the above exception, another exception occurred:
+
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
+    result = self.fn(*self.args, **self.kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
+    job.run()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 62, in run
+    self.push()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 113, in push
+    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 64, in wrapper
+    raise CommError(message, err).with_traceback(sys.exc_info()[2])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+wandb.errors.CommError: 'NoneType' object is not subscriptable
+2023-02-14 17:36:33,715 ERROR   Thread-12 (_thread_body):57839 [step_upload.py:_handle_event():141] Failed to upload file: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/requirements.txt
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+TypeError: 'NoneType' object is not subscriptable
+
+During handling of the above exception, another exception occurred:
+
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
+    result = self.fn(*self.args, **self.kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
+    job.run()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 62, in run
+    self.push()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 113, in push
+    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 64, in wrapper
+    raise CommError(message, err).with_traceback(sys.exc_info()[2])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+wandb.errors.CommError: 'NoneType' object is not subscriptable
+2023-02-14 17:36:33,718 ERROR   Thread-12 (_thread_body):57839 [step_upload.py:_handle_event():141] Failed to upload file: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/conda-environment.yaml
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+TypeError: 'NoneType' object is not subscriptable
+
+During handling of the above exception, another exception occurred:
+
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
+    result = self.fn(*self.args, **self.kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
+    job.run()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 62, in run
+    self.push()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 113, in push
+    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 64, in wrapper
+    raise CommError(message, err).with_traceback(sys.exc_info()[2])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+wandb.errors.CommError: 'NoneType' object is not subscriptable
+2023-02-14 17:36:33,722 ERROR   Thread-12 (_thread_body):57839 [step_upload.py:_handle_event():141] Failed to upload file: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/config.yaml
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+TypeError: 'NoneType' object is not subscriptable
+
+During handling of the above exception, another exception occurred:
+
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
+    result = self.fn(*self.args, **self.kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
+    job.run()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 62, in run
+    self.push()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 113, in push
+    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 64, in wrapper
+    raise CommError(message, err).with_traceback(sys.exc_info()[2])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+wandb.errors.CommError: 'NoneType' object is not subscriptable
+2023-02-14 17:36:33,725 ERROR   Thread-12 (_thread_body):57839 [step_upload.py:_handle_event():141] Failed to upload file: /home/zhangjinrong/program/Torch_Template/wandb/run-20230214_170826-5jufynrf/files/output.log
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+TypeError: 'NoneType' object is not subscriptable
+
+During handling of the above exception, another exception occurred:
+
+Traceback (most recent call last):
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
+    result = self.fn(*self.args, **self.kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 235, in run_and_notify
+    job.run()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 62, in run
+    self.push()
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 113, in push
+    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 64, in wrapper
+    raise CommError(message, err).with_traceback(sys.exc_info()[2])
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 26, in wrapper
+    return func(*args, **kwargs)
+  File "/home/zhangjinrong/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1762, in upload_urls
+    run_obj = query_result["model"]["bucket"]
+wandb.errors.CommError: 'NoneType' object is not subscriptable
